language: node_js

notifications:
  email: false

node_js:
  - '8'

env:
  matrix:
    - PACKAGE=jsx-render

before_install:
  - npm install -g lerna

install:
  - lerna bootstrap

script:
  - npm run test --prefix packages/$PACKAGE
